apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: awscontainerday
  labels:
    app: hello-world-svc
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30036
      name: hello-world
  selector:
    app: hello-world-d